{
 "title": "Cluster overview",
 "description": "This dashboard can help troubleshooting issue in k8s cluster at cluster, node and namespace level.",
 "tags": [
  "kubernetes",
  "k8s",
  "namespace"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "query_result(kube_namespace_labels)"
   },
   {
    "name": "container",
    "query": "kube_pod_container_info{namespace=\"$namespace\"}"
   },
   {
    "name": "duration",
    "query": "10m,30m,1h,2h,6h,12h,1d,2d,5d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster SLO and Error budget",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster control plane SLO over $duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$duration:5m])\n)"
      }
     ]
    },
    {
     "title": "Cluster control plane error budget remaining over $duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "\n\n(( avg(avg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$duration:5m])\n)) - 0.98999999999999999 ) \n* \navg((time() - timestamp(up{job=\"apiserver\",namespace=\"default\",service=\"kubernetes\"} offset $duration)))\n\n"
      }
     ]
    },
    {
     "title": "Promtheus monitoring SLO over $duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\navg_over_time((sum without ()(kube_pod_status_ready{namespace=\"monitoring\",pod=\"prometheus-prometheus-operator-prometheus-0\",condition=\"true\"}) \n/ \ncount without ()(kube_pod_status_ready{namespace=\"monitoring\",pod=\"prometheus-prometheus-operator-prometheus-0\"}))[$duration:5m])\n)"
      }
     ]
    }
   ]
  },
  { "title": "Overall cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Cluster age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - kube_service_created{namespace=\"default\",service=\"kubernetes\"})"
    }
   ]
  },
  {
   "title": "Namespaces ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Total pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "burstable  pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Besteffort  pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ReadOnly PVC",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_readonly != 0) "
    }
   ]
  },
  {
   "title": "cluster  node details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))"
    },
    {
     "expr": "((label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))  -  (label_replace((node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))) /  (label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\")) "
    },
    {
     "expr": "max\n  by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\n"
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" }
   ]
  },
  {
   "title": "Blackbox TCP-probe",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{ target }}" }
   ]
  },
  {
   "title": "Cluster health details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "cluster node readiness",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Overall memory usage in cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod!=\"POD\",namespace!=\"\"})",
       "legendFormat": "Total memory used"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
       "legendFormat": "Total memory in cluster"
      }
     ]
    },
    {
     "title": "Waiting/Terminated pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by(namespace,reason) (kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 )",
       "legendFormat": "TERMINATED::{{reason}}::{{namespace}}"
      },
      {
       "expr": "count by(namespace,reason) (kube_pod_container_status_waiting_reason !=0 )",
       "legendFormat": "WAITING::{{reason}}::{{namespace}}"
      },
      {}
     ]
    },
    {
     "title": "Node  wise load in cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load5 + on(instance) group_left(nodename) \nnode_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory usage in cluster by node",
     "type": "graph",
     "description": "This panel shows node memory usage:\n\nnode_memory_MemTotal - node_memory_MemAvailable",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info) - (node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory usage by namespace in cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(sum by (namespace)(container_memory_usage_bytes{pod!=\"POD\",namespace!=\"\"}))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Overall CPU usage in cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(sum by (instance) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info)",
       "legendFormat": "Total Used CPU in cluster"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
       "legendFormat": "Total CPU in cluster"
      }
     ]
    },
    {
     "title": "Node CPU usage[5m] in cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (instance,nodename) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info)",
       "legendFormat": "{{nodename}} "
      }
     ]
    },
    {
     "title": "Pod startup latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " histogram_quantile(0.99,\n  sum by(instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{job=\"kubelet\",metrics_path=\"/metrics\"}[5m])))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"}",
       "legendFormat": "{{node}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace $namespace details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace $namespace SLO over $duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"$namespace\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"$namespace\"}))[$duration:5m])\n)"
      }
     ]
    },
    {
     "title": "Error budget remaining for namespace: $namespace  over $duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 7, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "\n\n(( avg(avg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"$namespace\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"$namespace\"}))[$duration:5m])\n)) - 0.98999999999999999 ) \n* \navg((time() - timestamp(up{job=\"apiserver\",namespace=\"default\",service=\"kubernetes\"} offset $duration)))\n\n"
      }
     ]
    },
    {
     "title": "total  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{namespace=\"$namespace\",container=\"POD\"}))"
      }
     ]
    },
    {
     "title": "$namespace namespace creation time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(time() - kube_namespace_created{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_deployment_created{namespace=\"$namespace\"})",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Ready pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_ready{namespace=\"$namespace\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Terminated pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_terminated{namespace=\"$namespace\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Waiting pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_waiting{namespace=\"$namespace\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PVCs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info{namespace=\"$namespace\"}) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "burstable  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\",container=\"POD\"}))"
      }
     ]
    },
    {
     "title": "Besteffort  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Guaranteed  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(container_spec_memory_reservation_limit_bytes{namespace=\"$namespace\",container=\"POD\",id!~\".*.burstable.*|.*.besteffort.*\",id!~\".*.scope\",pod!=\"\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total CPU usage in $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(namespace) (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": " CPU usage by pod in $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total CPU requests in namespace $namespace",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 15, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(namespace:kube_pod_container_resource_requests_cpu_cores:sum{namespace=\"$namespace\"}) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU throttling",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum\n  by( namespace) (increase(container_cpu_cfs_throttled_periods_total{container!=\"\",namespace=\"$namespace\"}[5m]))\n  / sum by( namespace) (increase(container_cpu_cfs_periods_total{namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total memory requests in namespace $namespace",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 15, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum{namespace=\"$namespace\"}) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total memory  usage by pods in $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(namespace) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "memory  usage by pods in $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(pod) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "API server errors for namespace $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(name) (increase(aggregator_unavailable_apiservice_count{namespace=\"$namespace\"}[5m])) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "pod restarts in $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[2m]) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "pod $container state in $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_pod_container_status_ready{namespace=\"$namespace\",container=\"$container\"}) ",
       "legendFormat": "READY::{{pod}}::container $container"
      },
      {
       "expr": "(kube_pod_container_status_waiting{namespace=\"$namespace\",container=\"$container\"})",
       "legendFormat": "WAITING::{{pod}}::container $container "
      },
      {
       "expr": "(kube_pod_container_status_terminated{namespace=\"$namespace\",container=\"$container\"})",
       "legendFormat": "TERMINATED::{{pod}}::container $container"
      }
     ]
    },
    {
     "title": "PVCs available capacity in namespacee $namespace",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_available_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=\"$namespace\"}\n  / kubelet_volume_stats_capacity_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=\"$namespace\"}\n ",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "persistentvolumeclaim status in namespace $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 9, "y": 54 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(kube_persistentvolumeclaim_access_mode{namespace=\"$namespace\"})",
       "legendFormat": "{{access_mode}}::{{persistentvolumeclaim}}"
      },
      {
       "expr": "kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\",phase=\"Bound\"}",
       "legendFormat": "Bound::{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "PVCs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 17, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Failed\",namespace=\"$namespace\"} != 0) "
      }
     ]
    },
    {
     "title": "PVCs Pending",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 20, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Pending\",namespace=\"$namespace\"} != 0)"
      }
     ]
    },
    {
     "title": "Resource Quota in namespace $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kube_resourcequota{namespace=\"$namespace\",resource=~\".*.memory.*\"}/1024^3",
       "legendFormat": "{{type}}::{{resource}} GB"
      },
      {
       "expr": "kube_resourcequota{namespace=\"$namespace\",resource=~\".*.storage.*\"}/1024^3",
       "legendFormat": "{{type}}::{{resource}} GB"
      }
     ]
    },
    {
     "title": "pods running in $namespace",
     "type": "table",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{namespace=\"$namespace\"}"
      },
      {
       "expr": "sum\n  by(pod) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"})",
       "legendFormat": "Memory usage"
      },
      {
       "expr": "kube_pod_info{namespace=\"$namespace\"}"
      },
      {
       "expr": "time() - kube_pod_start_time{namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Ingress in $namespace",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kube_ingress_path{namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  }
 ]
}