
# chart: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-blackbox-exporter
#        https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
restartPolicy: Always
replicas: 1
pspEnabled: true

# https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md
config:
  # https://lyz-code.github.io/blue-book/devops/prometheus/blackbox_exporter/#blackbox-exporter-probes

  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        no_follow_redirects: false
        preferred_ip_protocol: "ip4"
        tls_config:
          insecure_skip_verify: true
    http_post_2xx:
      prober: http
      http:
      method: POST
    tcp_connect:
      prober: tcp
    pop3s_banner:
      prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
    ssh_banner:
      prober: tcp
      tcp:
        query_response:
        - expect: "^SSH-2.0-"
    icmp:
      prober: icmp
serviceMonitor:
  enabled: true
  targets: 
    ${indent(4,targets)}

prometheusRule:
  enabled: false